"""add power_level to heroes

Revision ID: 49e3e2487a13
Revises: 8e0846bd353a
Create Date: 2026-09-07 11:42:56.921093

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49e3e2487a13"
down_revision: str | Sequence[str] | None = "8e0846bd353a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("heroes", sa.Column("power_level", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("heroes", "power_level")
    # ### end Alembic commands ###
